If bison and flex are not found we bail out. The objective is to have a fully reentrant libconf. Why? Mostly it is a hope that we might someday fork off libconf and then such a requirement is necessary. However, I have chosen to set that requirement for qadsl as well. After all, the license is GPL so we also want to do some propaganda as well - and hey, good old lex is really not worth the trouble anyway.
Dunno if byacc can generate reentrant code though, must add to TODO:
"Check if byacc also generate reentrant code - if so, add to
checklist in configure.in".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3245,6 +3245,15 @@ fi
 if test "$LEX" = :; then
   LEX=${am_missing_run}flex
 fi
+if test "$LEX" != flex; then
+   { { echo "$as_me:$LINENO: error: Cannot find Flex, aborting.
+qadsl, or rather libconf, needs Bison to generate reentrant code.
+See \`config.log' for more details." >&5
+echo "$as_me: error: Cannot find Flex, aborting.
+qadsl, or rather libconf, needs Bison to generate reentrant code.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -3285,6 +3294,17 @@ fi
   test -n "$YACC" && break
 done
 test -n "$YACC" || YACC="yacc"
+
+if test "$YACC" != "bison -y"; then
+   { { echo "$as_me:$LINENO: error: Cannot find Bison, aborting.
+qadsl, or rather libconf, needs Bison to generate reentrant code.
+See \`config.log' for more details." >&5
+echo "$as_me: error: Cannot find Bison, aborting.
+qadsl, or rather libconf, needs Bison to generate reentrant code.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 
 if test -n "$ac_tool_prefix"; then
