Test for GCC and its features in a more confined way.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3245,15 +3245,6 @@ fi
 if test "$LEX" = :; then
   LEX=${am_missing_run}flex
 fi
-if test "$LEX" != flex; then
-   { { echo "$as_me:$LINENO: error: Cannot find Flex, aborting.
-qadsl, or rather libconf, needs Bison to generate reentrant code.
-See \`config.log' for more details." >&5
-echo "$as_me: error: Cannot find Flex, aborting.
-qadsl, or rather libconf, needs Bison to generate reentrant code.
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -3295,17 +3286,116 @@ fi
 done
 test -n "$YACC" || YACC="yacc"
 
-if test "$YACC" != "bison -y"; then
-   { { echo "$as_me:$LINENO: error: Cannot find Bison, aborting.
-qadsl, or rather libconf, needs Bison to generate reentrant code.
-See \`config.log' for more details." >&5
-echo "$as_me: error: Cannot find Bison, aborting.
-qadsl, or rather libconf, needs Bison to generate reentrant code.
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
+
+if test "$GCC" = "yes" ; then
+    # set GCC compiler options that should work with all versions
+    CFLAGS="${CFLAGS} -Wall -pedantic -fpic -Wno-long-long"
+    SHAREDLIB_LDFLAGS="-shared ${SHAREDLIB_LDFLAGS}"
+    DEPEND_CCFLAGS="-MM"
+
+    # -std=c99 is only supported in later releases of GCC and causes
+    # Linux headers to go into strict ANSI mode, dropping non-ANSI functions
+    # so we have to fall back to -std=gnu99 if c99 doesn't work
+    save_CFLAGS="${CFLAGS}"
+    CFLAGS="${CFLAGS} -std=c99 -Werror-implicit-function-declaration"
+    echo "$as_me:$LINENO: checking whether GNU cc -std=c99 option works" >&5
+echo $ECHO_N "checking whether GNU cc -std=c99 option works... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <string.h> char *a; a = strdup("foo");
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6 ; CFLAGS="$save_CFLAGS -std=c99"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	CFLAGS="$save_CFLAGS -std=gnu99 -Werror-implicit-function-declaration"
+    	echo "$as_me:$LINENO: checking whether GNU cc -std=gnu99 option works" >&5
+echo $ECHO_N "checking whether GNU cc -std=gnu99 option works... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <string.h> char *a; a = strdup("foo");
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6 ; CFLAGS="$save_CFLAGS -std=gnu99"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6 ; CFLAGS="$save_CFLAGS"
 fi
-
-
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
@@ -3387,8 +3477,6 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
-
-CFLAGS="-std=gnu99"
 
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
